# Generated by Django 5.0.1 on 2024-01-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='courses',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, to='college_app.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department'),
        ),
    ]
